/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.testepi;

import DAO.ProdutosDAO;
import DAO.VendaDAO;
import com.mycompany.testepi.MODEL.Cliente;
import com.mycompany.testepi.MODEL.Produtos;
import com.mycompany.testepi.MODEL.Venda;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wenderson
 */
public class TelaVendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaVendas
     */
    public TelaVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnBusca = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtCpfCliente = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        boxTipoPag = new javax.swing.JComboBox<>();
        panelParcelamento = new javax.swing.JPanel();
        lblParcelas = new javax.swing.JLabel();
        boxQntParcelas = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        lblValor2 = new javax.swing.JLabel();
        lblValorFinal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        btnConcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbldataVenda = new javax.swing.JLabel();
        jdcDataVenda = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        lblCodProd = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        lblNomeProd = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        lblQnt = new javax.swing.JLabel();
        txtQnt = new javax.swing.JTextField();
        lblValorUnit = new javax.swing.JLabel();
        txtValorUnit = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        btnExcluirItem = new javax.swing.JButton();
        btnAdicionarItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Alterar");

        jButton1.setText("Excluir");

        jButton2.setText("Cadastrar");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela de Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("CPF do cliente:");

        jLabel8.setText("Selecionar Cliente:");

        BtnBusca.setText("Buscar");
        BtnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscaActionPerformed(evt);
            }
        });

        jLabel9.setText("Cliente: ");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        try {
            txtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfClienteActionPerformed(evt);
            }
        });
        txtCpfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BtnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(BtnBusca)
                    .addComponent(txtCpfCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tipo de Pagamento:"));

        boxTipoPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma opção>", "Dinheiro", "Cartão de Débito", "Cartão de Crédito á Vista", "Cartão de Crédito Parcelado" }));
        boxTipoPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoPagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(boxTipoPag, 0, 210, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(boxTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        panelParcelamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Parcelamento:"));

        boxQntParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2x ", "3x ", "4x", "5x ", "6x " }));
        boxQntParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxQntParcelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParcelamentoLayout = new javax.swing.GroupLayout(panelParcelamento);
        panelParcelamento.setLayout(panelParcelamentoLayout);
        panelParcelamentoLayout.setHorizontalGroup(
            panelParcelamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParcelamentoLayout.createSequentialGroup()
                .addComponent(lblParcelas)
                .addGap(60, 60, 60)
                .addComponent(boxQntParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panelParcelamentoLayout.setVerticalGroup(
            panelParcelamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParcelamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelParcelamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxQntParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParcelas))
                .addGap(18, 18, 18))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblValor2.setText("Valor Final: ");

        lblValorFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblValorFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorFinal.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValor2)
                .addGap(119, 119, 119))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblValorFinal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblValor2)
                .addGap(18, 18, 18)
                .addComponent(lblValorFinal)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód Produto", "Produto", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ));
        tblItens.setEnabled(false);
        jScrollPane2.setViewportView(tblItens);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIniciar.setText("Iniciar Venda");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnConcluir.setText("Concluir Venda");
        btnConcluir.setEnabled(false);
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel11.setText("Cod Venda: ");

        lbldataVenda.setText("Data da Venda:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar)
                .addGap(18, 18, 18)
                .addComponent(btnConcluir)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(87, 87, 87)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldataVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConcluir)
                        .addComponent(btnIniciar)
                        .addComponent(btnCancelar)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbldataVenda)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCodProd.setText("Cód do Produto:");

        txtCodProd.setEnabled(false);
        txtCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdActionPerformed(evt);
            }
        });
        txtCodProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProdKeyTyped(evt);
            }
        });

        lblNomeProd.setText("Nome do Produto:");

        txtNomeProd.setEnabled(false);
        txtNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdActionPerformed(evt);
            }
        });

        lblQnt.setText("Quantidade:");

        txtQnt.setEnabled(false);
        txtQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntActionPerformed(evt);
            }
        });
        txtQnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQntKeyTyped(evt);
            }
        });

        lblValorUnit.setText("Valor Unitário:");

        txtValorUnit.setEnabled(false);
        txtValorUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUnitActionPerformed(evt);
            }
        });

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnExcluirItem.setText("Excluir Item");
        btnExcluirItem.setEnabled(false);
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        btnAdicionarItem.setText("Adicionar Item");
        btnAdicionarItem.setEnabled(false);
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(lblQnt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lblCodProd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(lblValorUnit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lblNomeProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProd)
                    .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeProd)
                    .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQnt)
                            .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorUnit))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))))
        );

        jLabel1.setText("Itens adicionados:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelParcelamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelParcelamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     *
     * Método executado quando o botão de busca é clicado.
     *
     * @param evt O evento de clique no botão.
     */
    private void BtnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscaActionPerformed
        String cpf = txtCpfCliente.getText().replace(".", "").replace(".", "").replace("-", "");

        VendaDAO pg = new VendaDAO();

        Cliente busca = (pg.PesquisarCliente(cpf));

        if (busca == null) {
            JOptionPane.showMessageDialog(rootPane, "Cliente não cadastrado");
        } else {
            txtCliente.setText(busca.getNome());

        }
    }//GEN-LAST:event_BtnBuscaActionPerformed
    /**
     *
     * Método executado quando o campo de texto do cliente é acionado.
     *
     * @param evt O evento de ação no campo de texto.
     */
    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void boxTipoPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoPagActionPerformed
        /**
         *
         * Método executado quando o tipo de pagamento é selecionado.
         *
         * @param evt O evento de seleção do tipo de pagamento.
         */

    }//GEN-LAST:event_boxTipoPagActionPerformed

    private void boxQntParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxQntParcelasActionPerformed

    }//GEN-LAST:event_boxQntParcelasActionPerformed
     /**
     *
     * Método executado quando o número de parcelas é selecionado.
     *
     * @param evt O evento de seleção do número de parcelas.
     */
    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked

    }//GEN-LAST:event_btnIniciarMouseClicked
    /**
     *
     * Método executado quando o botão "Iniciar" é clicado.
     *
     * @param evt O evento de clique no botão "Iniciar".
     */
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        habilitarCampos(true);
        limpaCampos();
    }//GEN-LAST:event_btnIniciarActionPerformed
    /**
     *
     * Método executado quando o botão "Concluir" é acionado. Método usado para
     * concluir a compra e checar se há estoque do produto ou não
     *
     * @param evt O evento de ação no botão "Concluir".
     */
    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        if (tblItens.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Insira ao menos 1 produto");
            return;
        }

        if (jdcDataVenda.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Insira a data da venda");
            return;
        }

        if (txtCpfCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira o CPF do cliente");
            return;
        }

        if (boxTipoPag.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione o tipo de pagamento");
            return;
        }

        try {
            ArrayList<Venda> listaItens = new ArrayList<Venda>();

            if (tblItens.getRowCount() > 0) {
                for (int i = 0; i < tblItens.getRowCount(); i++) {
                    Venda v = new Venda();

                    v.setCodProduto(Integer.parseInt(tblItens.getValueAt(i, 0).toString()));
                    v.setNomeProduto(tblItens.getValueAt(i, 1).toString());
                    v.setQuantidade(Integer.parseInt(tblItens.getValueAt(i, 2).toString()));
                    v.setValorUnitario(Double.parseDouble(tblItens.getValueAt(i, 3).toString()));
                    v.setValorTotal(Double.parseDouble(tblItens.getValueAt(i, 4).toString()));

                    listaItens.add(v);
                }
            }

            ProdutosDAO estoqueDAO = new ProdutosDAO();
            boolean estoqueDisponivel = true;

            for (Venda venda : listaItens) {
                int codProduto = venda.getCodProduto();
                int quantidade = venda.getQuantidade();

                // Verifica se há estoque suficiente para o produto
                if (!estoqueDAO.verificarEstoqueSuficiente(codProduto, quantidade)) {
                    estoqueDisponivel = false;
                    JOptionPane.showMessageDialog(this, "Produto sem estoque!");
                    break;
                }
            }

            if (estoqueDisponivel) {
                // Atualiza o estoque e salva a venda
                for (Venda venda : listaItens) {
                    int codProduto = venda.getCodProduto();
                    int quantidade = venda.getQuantidade();

                    estoqueDAO.atualizarEstoque(codProduto, quantidade);
                }

                Date data = jdcDataVenda.getDate();
                String nome = txtCliente.getText();
                String cpf = txtCpfCliente.getText().replace(".", "").replace(".", "").replace("-", "");
                String tipoPag = boxTipoPag.getSelectedItem().toString();

                Double valorFinal = Double.parseDouble(lblValorFinal.getText());

                Venda objVendas = new Venda();

                objVendas.setListaItens(listaItens);
                objVendas.setDataVenda(data);
                objVendas.setNome(nome);
                objVendas.setCpf(cpf);
                objVendas.setTipo_pag(tipoPag);

                objVendas.setFinal(valorFinal);

                VendaDAO salvarVendasDAO = new VendaDAO();
                salvarVendasDAO.Salvar(objVendas);
                JOptionPane.showMessageDialog(this, "Venda concluida!");
            }
        } catch (NumberFormatException e) {
            // Trate a exceção de conversão de número aqui
        }

        limpaCampos();

    }//GEN-LAST:event_btnConcluirActionPerformed
    /**
     *
     * Método executado quando o botão "Cancelar" é acionado Utilizado para
     * cancelar a compra
     *
     * @param evt O evento de ação no botão "Concluir".
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    /**
     *
     * Método executado quando o campo de código do produto é acionado.
     *
     * @param evt O evento de ação no campo de código do produto.
     */
    private void txtCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdActionPerformed

    }//GEN-LAST:event_txtCodProdActionPerformed
    /**
     *
     * Método executado quando uma tecla é pressionada no campo de código do
     * produto.
     *
     * @param evt O evento de pressionar uma tecla no campo de código do
     * produto.
     */
    private void txtCodProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdKeyTyped

    }//GEN-LAST:event_txtCodProdKeyTyped
     /**
     *
     * Método executado quando o campo de nome do produto é acionado.
     *
     * @param evt O evento de ação no campo de nome do produto.
     */
    private void txtNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdActionPerformed

    }//GEN-LAST:event_txtNomeProdActionPerformed
    /**
     *
     * Método executado quando o campo de quantidade é acionado.
     *
     * @param evt O evento de ação no campo de quantidade.
     */
    private void txtQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQntActionPerformed
    /**
     *
     * Método executado quando uma tecla é pressionada no campo de quantidade.
     *
     * @param evt O evento de pressionar uma tecla no campo de quantidade.
     */
    private void txtQntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQntKeyTyped

    }//GEN-LAST:event_txtQntKeyTyped

    private void txtValorUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnitActionPerformed
    /**
     *
     * Método executado quando o botão de busca é acionado. Utilizado para fazer
     * a busca do produto pelo código na hora da venda.
     *
     * @param evt O evento de ação no botão de busca.
     */
    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        if (txtCodProd.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o código do produto para busca-lo");
        }

        try {
            int id = Integer.parseInt(txtCodProd.getText());

            VendaDAO v = new VendaDAO();

            Produtos busca = (v.PesquisarProdutoCod(id));

            txtNomeProd.setText(busca.getNome());
            txtValorUnit.setText(String.valueOf(busca.getPreco()));
        } catch (NumberFormatException e) {

        }

    }//GEN-LAST:event_btnBuscaActionPerformed
    /**
     *
     * Método executado quando o botão de excluir item é acionado.
     *
     * @param evt O evento de ação no botão de excluir item.
     */
    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        ((DefaultTableModel) tblItens.getModel()).removeRow(tblItens.getSelectedRow());

        Total(false);
    }//GEN-LAST:event_btnExcluirItemActionPerformed
    /**
     *
     * Método executado quando o botão de adicionar item é acionado. Utilizado
     * para adicionar itens a tabela/carinho de compra.
     *
     * @param evt O evento de ação no botão de adicionar item.
     */
    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        if (txtCodProd.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o código do produto");
            return;
        }
        if (txtQnt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a quantidade do produto");
            return;
        }
        if (txtValorUnit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o valor unitário do Produto");
            return;
        }

        String codProd = txtCodProd.getText().trim();
        String nomeProd = txtNomeProd.getText().trim();
        String qnt = txtQnt.getText().trim();
        String valorUnit = txtValorUnit.getText().trim();

        DefaultTableModel tbItens = (DefaultTableModel) tblItens.getModel();

        tbItens.addRow(new String[]{codProd, nomeProd, qnt, valorUnit});

        txtCodProd.setText("");
        txtNomeProd.setText("");
        txtQnt.setText("");
        txtValorUnit.setText("");

        txtCodProd.requestFocus();

        double qnt1;
        double valorUnit1;

        int cont = tblItens.getRowCount();

        for (int i = 0; i < cont; i++) {
            qnt1 = Double.parseDouble(tblItens.getValueAt(i, 2).toString());
            valorUnit1 = Double.parseDouble(tblItens.getValueAt(i, 3).toString());
            double ValorTotal = qnt1 * valorUnit1;
            tblItens.setValueAt(String.valueOf(ValorTotal), i, 4);
        }
        Total(true);
    }//GEN-LAST:event_btnAdicionarItemActionPerformed
    /**
     *
     * Método executado quando o campo de CPF do cliente é acionado.
     *
     * @param evt O evento de ação no campo de CPF do cliente.
     */
    private void txtCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfClienteActionPerformed

    }//GEN-LAST:event_txtCpfClienteActionPerformed
    /**
     *
     * Método executado quando uma tecla é pressionada no campo de CPF do
     * cliente.
     *
     * @param evt O evento de pressionar uma tecla no campo de CPF do cliente.
     */
    private void txtCpfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfClienteKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE
                && c != KeyEvent.VK_ENTER)) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Digite apenas números");

            txtCpfCliente.setText("");
        }
    }//GEN-LAST:event_txtCpfClienteKeyTyped
    /**
     * Função que demonstra o valor total
     *
     * @param status
     */
    private void Total(boolean status) {
        double valorTotal = 0;
        int cont = tblItens.getRowCount();

        if (status = true) {
            for (int i = 0; i < cont; i++) {
                valorTotal += Double.parseDouble(tblItens.getValueAt(i, 4).toString());
            }

            lblValorFinal.setText(String.valueOf(valorTotal));
        } else {
            for (int i = 0; i < cont; i++) {
                valorTotal -= Double.parseDouble(tblItens.getValueAt(i, 4).toString());
            }

            lblValorFinal.setText(String.valueOf(valorTotal));
        }
    }

    /**
     * função que habilita os campos necessários
     *
     * @param evt
     */
    private void habilitarCampos(boolean status) {
        btnIniciar.setEnabled(!status);
        btnConcluir.setEnabled(status);
        btnCancelar.setEnabled(status);
        txtCodProd.setEnabled(status);
        txtNomeProd.setEnabled(status);
        txtQnt.setEnabled(status);
        txtValorUnit.setEnabled(status);
        btnAdicionarItem.setEnabled(status);
        btnExcluirItem.setEnabled(status);
        tblItens.setEnabled(status);
        txtCpfCliente.setEnabled(status);
        txtCliente.setEnabled(status);

        boxTipoPag.setEnabled(status);
        jdcDataVenda.setEnabled(status);

    }

    /**
     * Função que limpa os campos de texto
     *
     * @param evt
     */
    private void limpaCampos() {
        txtCodProd.setText("");
        txtNomeProd.setText("");
        txtQnt.setText("");
        txtValorUnit.setText("");
        txtCliente.setText("");
        txtCpfCliente.setText("");
        jdcDataVenda.setDate(null);
        boxTipoPag.setSelectedIndex(0);
        DefaultTableModel tbItens = (DefaultTableModel) tblItens.getModel();
        tbItens.setNumRows(0);
        lblValorFinal.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBusca;
    private javax.swing.JComboBox<String> boxQntParcelas;
    private javax.swing.JComboBox<String> boxTipoPag;
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser jdcDataVenda;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblNomeProd;
    private javax.swing.JLabel lblParcelas;
    private javax.swing.JLabel lblQnt;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValorFinal;
    private javax.swing.JLabel lblValorUnit;
    private javax.swing.JLabel lbldataVenda;
    private javax.swing.JPanel panelParcelamento;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JFormattedTextField txtCpfCliente;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtQnt;
    private javax.swing.JTextField txtValorUnit;
    // End of variables declaration//GEN-END:variables
}
