/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.testepi;

import DAO.RelatorioDAO;
import com.mycompany.testepi.MODEL.Relatorio;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel Barbosa Maia
 */
public class TelaRelatorios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelBusca = new javax.swing.JPanel();
        lblDataInicial = new javax.swing.JLabel();
        lblDataFinal = new javax.swing.JLabel();
        jdcDIN = new com.toedter.calendar.JDateChooser();
        jdcDF = new com.toedter.calendar.JDateChooser();
        btnPesquisar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RelatorioSintetico = new javax.swing.JTable();
        btnRANA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RelatorioAnalitico = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Relatórios");

        jPanelBusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca"));

        lblDataInicial.setText("Data inicial:");

        lblDataFinal.setText("Data final:");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscaLayout = new javax.swing.GroupLayout(jPanelBusca);
        jPanelBusca.setLayout(jPanelBuscaLayout);
        jPanelBuscaLayout.setHorizontalGroup(
            jPanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcDF, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jdcDIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanelBuscaLayout.setVerticalGroup(
            jPanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBuscaLayout.createSequentialGroup()
                        .addGroup(jPanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcDIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatorio Sintético"));

        RelatorioSintetico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Cliente", "Valor venda"
            }
        ));
        jScrollPane1.setViewportView(RelatorioSintetico);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRANA.setText("Ver relatorio análitico");
        btnRANA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRANAActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor Total:");

        lblValorTotal.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRANA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRANA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório Sintético", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatorio Análitico"));

        RelatorioAnalitico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Cliente", "Produto", "Quantidade", "Valor venda"
            }
        ));
        jScrollPane2.setViewportView(RelatorioAnalitico);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório Análitico ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    /**
     * Função que pesquisa e emite o relatorio sintético
     *
     * @param evt
     */
    
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
   
        ArrayList<String> erros = new ArrayList();
        
        if (jdcDIN.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Insira a data do periodo");
            return;
        }
        if (jdcDF.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Insira a data do periodo");
            return;
        }
        
        // Obtenha as datas inicial e final selecionadas nos JDateChoosers
Date dataInicial = jdcDIN.getDate();
Date dataFinal = jdcDF.getDate();

// Verifique se as datas selecionadas são válidas
if (dataInicial != null && dataFinal != null) {
    // Converta as datas para o formato adequado para consulta no banco de dados
    java.sql.Date sqlDataInicial = new java.sql.Date(dataInicial.getTime());
    java.sql.Date sqlDataFinal = new java.sql.Date(dataFinal.getTime());

    // Consulte o banco de dados para obter os relatórios com as datas selecionadas
    ArrayList<Relatorio> lista = RelatorioDAO.listar(sqlDataInicial, sqlDataFinal);

    if (lista != null) {
        DefaultTableModel modelo = (DefaultTableModel) RelatorioSintetico.getModel();
        modelo.setRowCount(0);

        for (Relatorio relatorio : lista) {
            modelo.addRow(new String[]{
                String.valueOf(relatorio.getData()),
                String.valueOf(relatorio.getCliente()),
                String.valueOf(relatorio.getValor())
            });
        }
    }
}
exibirTotal(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed
 
    /**
     * Função que pesquisa e emite o relatorio análitico
     *
     * @param evt
     */
    
    private void btnRANAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRANAActionPerformed
         jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
        
        
        ArrayList<String> erros = new ArrayList();
        
        if (jdcDIN.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Insira a data do periodo");
            return;
        }
        if (jdcDF.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Insira a data do periodo");
            return;
        }
        
        // Obtenha as datas inicial e final selecionadas nos JDateChoosers
Date dataInicial = jdcDIN.getDate();
Date dataFinal = jdcDF.getDate();

// Verifique se as datas selecionadas são válidas
if (dataInicial != null && dataFinal != null) {
    // Converta as datas para o formato adequado para consulta no banco de dados
    java.sql.Date sqlDataInicial = new java.sql.Date(dataInicial.getTime());
    java.sql.Date sqlDataFinal = new java.sql.Date(dataFinal.getTime());

    // Consulte o banco de dados para obter os relatórios com as datas selecionadas
    ArrayList<Relatorio> lista = RelatorioDAO.listarANA(sqlDataInicial, sqlDataFinal);

    if (lista != null) {
        DefaultTableModel modelo = (DefaultTableModel) RelatorioAnalitico.getModel();
        modelo.setRowCount(0);

        for (Relatorio relatorio : lista) {
            modelo.addRow(new String[]{
                String.valueOf(relatorio.getData()),
                String.valueOf(relatorio.getCliente()),
                String.valueOf(relatorio.getProdutos()),
                String.valueOf(relatorio.getQuantidade()),
                String.valueOf(relatorio.getValor())
                   
            });
        }
    }
}
    }//GEN-LAST:event_btnRANAActionPerformed

  /**
 * Exibe o valor total dos dados presentes na tabela de relatório sintético.
 *
 * @param status true se o valor total deve ser calculado como soma, false se deve ser calculado como subtração.
 */
    
private void exibirTotal(boolean status) {
    double valorTotal = 0;
    int cont = RelatorioSintetico.getRowCount();

    if (status) {
        for (int i = 0; i < cont; i++) {
            valorTotal += Double.parseDouble(RelatorioSintetico.getValueAt(i, 2).toString());
        }

        lblValorTotal.setText(String.valueOf(valorTotal));
    } else {
        for (int i = 0; i < cont; i++) {
            valorTotal -= Double.parseDouble(RelatorioSintetico.getValueAt(i, 2).toString());
        }

        lblValorTotal.setText(String.valueOf(valorTotal));
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RelatorioAnalitico;
    private javax.swing.JTable RelatorioSintetico;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRANA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBusca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcDF;
    private com.toedter.calendar.JDateChooser jdcDIN;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblValorTotal;
    // End of variables declaration//GEN-END:variables
}
